### ISSUE TITLE
Use SQLAlchemy ORM to get object properties

### ISSUE THREAD

**Issue by cthoyt** [bio2bel/ec#11]
Rather than writing complicated queries, the SQLAlchemy ORM allows for automatic access to properties like they are python objects. Therefore, the following code:

https://github.com/bio2bel/ec/blob/fda63d0ef09f72fcfa1fb93c6f6fc317886b01c3/src/bio2bel_expasy/database.py#L154-L163

could become

```python3
def get_parent(self, enzyme_id): 
    """Returns the parent model of an enzyme if it exists, otherwise returns None. 

    Raises an IndexError if no enzyme is found with the matching identifier.
    
    :param str enzyme_id: An ExPASy identifier 
    :rtype: Optional[Enzyme]
    :raises: IndexError
    """ 
    enyzme = self.get_enzyme_by_id(enzyme_id)

    if enzyme is None:
        raise IndexError
        
    return enzyme.parent
```

Also, this example returns the model that represents the parent rather than the value itself. This makes a bit more generally useful. If you need a function that directly returns the string identifier, then you can use this function to implement it.

**Note**: this example makes use of the function added in my latest commit https://github.com/bio2bel/ec/commit/fda63d0ef09f72fcfa1fb93c6f6fc317886b01c3

There are other functions that could also benefit from using the ORM instead of writing nasty queries including:

https://github.com/bio2bel/ec/blob/fda63d0ef09f72fcfa1fb93c6f6fc317886b01c3/src/bio2bel_expasy/database.py#L174

https://github.com/bio2bel/ec/blob/fda63d0ef09f72fcfa1fb93c6f6fc317886b01c3/src/bio2bel_expasy/database.py#L182

https://github.com/bio2bel/ec/blob/fda63d0ef09f72fcfa1fb93c6f6fc317886b01c3/src/bio2bel_expasy/database.py#L200

**Comment by aramgrigoryan** [comment]
oooo koouul
