### ISSUE TITLE
Use a SQLAlchemy relationship for children

### ISSUE THREAD

**Issue by cthoyt** [bio2bel/ec#13]
The query in this function should be directly accessible by defining a `relationship` variable called `children` in `bio2bel_expasy.models.Enzyme` such that the function

https://github.com/bio2bel/ec/blob/fda63d0ef09f72fcfa1fb93c6f6fc317886b01c3/src/bio2bel_expasy/database.py#L209-L216

can be implemented as simply as

```python3
def get_children(self, expasy_id):
    """"Gets the children of an enzyme by its identifier

    :type str expasy_id: An expasy database identifier
    :rtype: list[Enzyme]
    """"
    enzyme = self.get_enzyme_by_id(expasy_id)
    return enzyme.children
```

**Comment by aramgrigoryan** [comment]
not needed for now
