### ISSUE TITLE
Parent not populated in database

### ISSUE THREAD

**Issue by cthoyt** [bio2bel/ec#15]
I just ran
```
bio2bel_expasy populate
bio2bel_expasy web
```

and there aren't any entries in the parents column. Also, each enzyme only has one parent so it should be reflected in the ORM relationship (uselist=False) and in the way that the entry is assigned (not with .append)

<img width="1032" alt="screen shot 2017-11-24 at 4 02 00 pm" src="https://user-images.githubusercontent.com/5069736/33215687-e047fd80-d130-11e7-9cc6-41b27f18fe33.png">

**Comment by aramgrigoryan** [comment]
yep, it just builds 3 to 4 layers

**Comment by aramgrigoryan** [comment]
https://github.com/bio2bel/expasy/commit/cc1338d39a04be7a83b39c823e552c1a7fc8ca4e
