### ISSUE TITLE
Use PyUniProt to incorporate members of Enzyme classes

### ISSUE THREAD

**Issue by cthoyt** [bio2bel/ec#5]
It's directly possible to iterate over all instances of each enzyme class through PyUniProt.

1. Generate final portion of EC tree
2. Generate EC - UniProt mapping (or even better, using PyUniProt it would be possible to generate an EC-HGNC mapping. Might as well do both if they're both easy)

**Comment by aramgrigoryan** [comment]
1. what is the "final portion" of EC tree?

**Comment by cthoyt** [comment]
The final portion is the 4th level, which refers to actual proteins that have the activities in the first 3 levels from the EXPASY tree. You can go through UniProt to get these annotations and use text parsing to infer the parents.

http://pyuniprot.readthedocs.io/en/latest/query_functions.html#ec-number

```
import pyuniprot
query = pyuniprot.query()
for ec in query.ec_number():
   # get actual EC number, infer the parent, and the annotated children
```

**Comment by aramgrigoryan** [comment]
i am gonna query only humans
as it takes forever and has a memory leak

**Comment by cthoyt** [comment]
which part? does it not provide a lazy iterator over the database?

because we fixed the memory leak with loading and now it only uses 117mb total :)

**Comment by aramgrigoryan** [comment]
it's looking fine now. seems to be working.. have to wait
