### ISSUE TITLE
Enrich BELGraph function

### ISSUE THREAD

**Issue by cthoyt** [bio2bel/ec#6]
Would like a function that takes a given BEL graph, finds all proteins in it, annotates their EC parents all the way up to root

**Comment by aramgrigoryan** [comment]
what is a "bell graph", how and where do i get it? need an example of it.

**Comment by cthoyt** [comment]
Bel graphs are produced by the parsing of a BEL script and are the "in-memory" model of the graph. We can also directly make additions and queries to these graphs so it would be nice to do this without having to serialized  and parse a whole bel script

**Comment by cthoyt** [comment]
Is there a commit reference for this?

**Comment by aramgrigoryan** [comment]
woops, dont know why i did this...
