### ISSUE TITLE
Add sample pyuniprot data to include in testing

### ISSUE THREAD

**Issue by cthoyt** [bio2bel/ec#8]
The test harness should also load the sample data using `PyUniProt`'s population function so then the functionality of this library that depends on `PyUniProt` can be properly tested

**Comment by aramgrigoryan** [comment]
cannot we just query with limit=N in tests?

**Comment by cthoyt** [comment]
@aramgrigoryan We're going to no use PyUniProt at all, if you still think that's possible.
